### PR TITLE
Fixed layout of external memory

### PR DESCRIPTION
**Pull request by zvonimir**
I am running SVCOMP to see if this has any effect on performance. We could maybe review it in the meantime.

### CODE REVIEW

**Comment by michael-emmi** [comment]
What about the declaration of `$EXTERNS_BOTTOM` from `SmackRep::getPrelude`? Shouldn’t this also be computed as on offset from `$GLOBALS_BOTTOM`?

Perhaps the variable name `SmackRep::externsBottom` is now misleading, since this is not the “bottom” but rather an ”offset.”

**Comment by zvonimir** [comment]
Good point. Check it out now.

**Comment by bitcalc** [comment]
When will this fix be available in the master branch?

**Comment by zvonimir** [comment]
There is a bit of delay due to xmas holidays. I'll start running SVCOMP benchmarks today to do a detailed performance comparison. I expect I'll merge this into the develop branch in 3-4 days from now. It'll only get merged into master with the next release.

**Comment by zvonimir** [comment]
On SVCOMP benchmarks, this branch actually does slightly better than develop. So I am merging this.

**Pull request merged**
