### PR TITLE
Made `build.sh` more resiliant, letting it resume after error.

### PR DESCRIPTION
**Pull request by cogumbreiro**
This is an attempt at handling issue #125.

### CODE REVIEW

**Comment by zvonimir** [comment]
Sorry about the delay. I've been super busy with an NSF large proposal (deadline is today).
I like your improvement, and I think this should probably be the default behavior. I certainly often manually turn off installation of a bunch of things using flags.
However, it would be great to be able to turn it off if and when needed. Could you maybe introduce a flag, maybe something like `--force-install` or something like that, which would overwrite the default behavior?
Thanks and it is great to have you (somewhat :)) on board!

**Comment by cogumbreiro** [comment]
Don't worry about the delay and thanks for accepting the push request.

Sure, I can introduce that flag that ignores the checks.

**Comment by cogumbreiro** [comment]
What do you think about calling the switch `--force-build` or `--skip-build-cache`?

My motivation for this is that the calling it `--force-install` might make sure the dependencies are installed no matter what, where what it actually does disabling some sort of build-cache.

Let me know which name you prefer `--force-install`.

**Comment by zvonimir** [comment]
I think that `--force-build` sounds good to me. You will have to resolve conflicts, but that should be relatively easy I think. Thanks a lot!
Side note: for some reason I occasionally do not get email notifications when people post comments to issues and pull requests on github. Hence I completely missed your comment. I still have to get to the bottom of this.

**Comment by michael-emmi** [comment]
Any reason this pull request is still hanging?

**Comment by zvonimir** [comment]
Well, the `force-build` flag we discussed above was not implemented, and so this never got merged. I still like the addition though since I often manually turn off installation of dependencies that I know I installed previously. However, silently skipping dependencies is probably not a good idea either.
I think that the right thing to do would be to issue a warning/note if installation of a dependency is skipped since it is already present (instead of implementing the `--force-build` flag).

**Comment by zvonimir** [comment]
We implemented a version of this.

**Pull request closed without merging**
