### PR TITLE
Initial support for SIMD vector operations.

### PR DESCRIPTION
**Pull request by michael-emmi**
This PR adds initial support for handling SIMD vector operations, as brought up in #172. Since many vector operations tend to introduce all kinds of bit casts, many programs cannot be proved correct without bit precision. This PR does not attempt to deal with bit precision. Instead, this PR focuses on providing the framework for handling all SIMD instructions, possibly yielding uninterpreted Boogie functions for those (bit cast) instructions that cannot be modeled precisely with Boogie integers.

### CODE REVIEW

**Comment by zvonimir** [comment]
This looks good to me. Really nice addition. You will have to fix some conflicts though. Then I think we can merge it.

**Comment by zvonimir** [comment]
I just remembered one more thing. Dan Liew told me recently that there is an LLVM pass that gets rid of (most) vector instructions. Have you looked into that at all? That would maybe be a good pass to run first.
I cannot find it at this point, but I could ask Dan about it.

**Comment by michael-emmi** [comment]
I assume he was referring to [scalarization](http://llvm.org/doxygen/Scalarizer_8cpp_source.html)?

While this does enable scalar optimizations like constant propagation in some cases, and can convert many vector operations to scalar operations, it doesn’t really attempt to get rid of vector types, e.g., as storage. For instance, consider the following function:
````c
__m128i foo(__m128i a, __m128i b) {
  return _mm_add_epi64(a,b);
}
````
Without scalarization this compiles to:
````ll
define <2 x i64> @foo(<2 x i64>, <2 x i64>) #0 {
  %3 = add <2 x i64> %0, %1
  ret <2 x i64> %3
}
````

With scalarization this compiles to:
````ll
define <2 x i64> @foo(<2 x i64>, <2 x i64>) #0 {
  %.i0 = extractelement <2 x i64> %0, i32 0
  %.i01 = extractelement <2 x i64> %1, i32 0
  %.i02 = add i64 %.i0, %.i01
  %.i1 = extractelement <2 x i64> %0, i32 1
  %.i13 = extractelement <2 x i64> %1, i32 1
  %.i14 = add i64 %.i1, %.i13
  %.upto0 = insertelement <2 x i64> undef, i64 %.i02, i32 0
  %3 = insertelement <2 x i64> %.upto0, i64 %.i14, i32 1
  ret <2 x i64> %3
}
````

Note that there are still vector types involved. And even if there were a pass to expand vector storage into scalar storage, this would still not handle the case of LLVM compiler intrinsics which have no built in mapping to scalar operations. For instance, consider the following function:

````c
__m128i foo(__m128i a, __m128i b) {
  return _mm_clmulepi64_si128(a,b,0);
}
````

Both with and without scalarization, this compiles to:
````ll
define <2 x i64> @foo(<2 x i64>, <2 x i64>) #0 {
  %3 = call <2 x i64> @llvm.x86.pclmulqdq(<2 x i64> %0, <2 x i64> %1, i8 0)
  ret <2 x i64> %3
}
````

Furthermore, getting rid of vectors may be counterproductive to the real purpose of my extension, which intends to model low-level code, as close to whats executed as possible.

**Comment by zvonimir** [comment]
Got it. Good, good, please merge it.

**Pull request merged**
