### PR TITLE
Enable multiple assertion checking when Corral is used

### PR DESCRIPTION
**Pull request by shaobo-he**
Previously, when `--max-violations` is set to a value greater than
1, Corral still reports at most one error trace. This is
because Corral continues the verification by turning a failing
assertion into an assumption. Therefore, even though there may
exist multiple calls to assertion checking procedures such as
`__VERIFIER_assert`, Corral only reports one of them. This commit
deals with this issue by leveraging Boogie's `/printInstrumented`
option to inline procedures containing assertions.

### CODE REVIEW

**Comment by zvonimir** [comment]
Question. Is this adding a dependency on Boogie even if a user wants to just use Corral?
Meaning, Boogie is maybe not available/installed in this case.

**Comment by zvonimir** [comment]
Wouldn't a better solution be to inline using an LLVM pass? Or to force inlining somehow during compilation?

**Comment by shaobo-he** [comment]
> Question. Is this adding a dependency on Boogie even if a user wants to just use Corral?
> Meaning, Boogie is maybe not available/installed in this case.

I think I saw a similar flag in Corral. Let me see if I can get it working.

**Comment by shaobo-he** [comment]
> Wouldn't a better solution be to inline using an LLVM pass? Or to force inlining somehow during compilation?

Currently, using LLVM's inline pass is not an option because `__SMACK_check_memory_safety` is implemented as Boogie code.

**Comment by shaobo-he** [comment]
> > Question. Is this adding a dependency on Boogie even if a user wants to just use Corral?
> > Meaning, Boogie is maybe not available/installed in this case.
> 
> I think I saw a similar flag in Corral. Let me see if I can get it working.

I can't find relevant options in Corral that archive similar goals.

**Comment by zvonimir** [comment]
See: https://github.com/boogie-org/corral/issues/138

**Comment by shaobo-he** [comment]
Closed this PR as the implementation is outdated.

**Pull request closed without merging**
