### PR TITLE
Add experimental support for Yices2

### PR DESCRIPTION
**Pull request by keram88**
This adds support for SMACK to leverage Yices2 support in Corral and Boogie.

We should merge this after we decide on which new versions of Corral and Boogie we are going to use.

### CODE REVIEW

**Comment by zvonimir** [comment]
Please refresh this with the current develop since there are merge conflicts. Then I'll review it. Thx!

**Comment by zvonimir** [comment]
@keram88 Please update this to the latest develop and clean up any merge conflicts. Then I'll review it. Thx!

**Comment by keram88** [comment]
I think I've addressed all concerns.
Yices doesn't support quantifiers, so memcpy, memset and memory safety don't work.
Yices also doesn't support bv2nat so would require `--bit-precise-pointers`.

**Comment by shaobo-he** [comment]
> I think I've addressed all concerns.
> Yices doesn't support quantifiers, so memcpy, memset and memory safety don't work.
> Yices also doesn't support bv2nat so would require `--bit-precise-pointers` for bit-vector code with pointers.

I think maybe Yices can handle memcpy and memset if we encode them using lambda terms. This is what I found in Mathias Preiner's thesis,

```
Other SMT solvers that employ a lazy SMT solving approach and natively support lambda terms 
such as CVC4 [3] or Yices [25] also treat them eagerly, similarly to UCLID, and eliminate all
occurrences of lambda terms by substituting them with their instantiated function body
(cf. C-style macros). 
```

I'm sure boolector supports it. But producing lambda terms is a task of Boogie. I don't know if Boogie already does it.

**Comment by zvonimir** [comment]
I just merged this. Let's continue the above discussion somewhere else. Thx!

**Pull request merged**
