### PR TITLE
Removed the occurrences of `TRAVIS` in bin/build.sh

### PR DESCRIPTION
**Pull request by shaobo-he**
They are no longer needed.

### CODE REVIEW

**Review by zvonimir — CHANGES_REQUESTED** [review]
You forgot one more place.

**Review by zvonimir — CHANGES_REQUESTED** [review]
There is also TRAVIS_ENV. Maybe we can remove that one too.

**Comment by shaobo-he** [comment]
> You forgot one more place.

Good catch. Fixed.

**Comment by shaobo-he** [comment]
> There is also TRAVIS_ENV. Maybe we can remove that one too.

This variable is actually used by GitHub Actions. So I renamed it.

**Review by zvonimir — APPROVED** [review]
Looks good to me.

**Pull request merged**
