### PR TITLE
Enable support for lib target name specification in Cargo.toml

### PR DESCRIPTION
**Pull request by shaobo-he**

### CODE REVIEW

**Comment by zvonimir** [comment]
Do examples we have here: https://github.com/smackers/smack/tree/master/examples/rust-cargo
still work?

**Comment by shaobo-he** [comment]
> Do examples we have here: https://github.com/smackers/smack/tree/master/examples/rust-cargo
> still work?

Yes, it still works.

**Comment by keram88** [comment]
This looks good to me. Maybe we'll have more issues like this, but deal with them as they come up.

**Review by keram88 — APPROVED** [review]

**Review by zvonimir — APPROVED** [review]
Looks good to me.

**Pull request merged**
