### PR TITLE
Add an option to enable targeted checking of specific functions

### PR DESCRIPTION
**Pull request by keram88**
This adds the ability to selectively check certain functions in a program, specifically:
* This adds the option `--checked-functions' which is a list of functions
  on which to do checking
* Not specifying this option enables all checks in every function
This partially addresses #713

### CODE REVIEW

**Review by shaobo-he — COMMENTED** [review]
Quick question: can we use a list of  regex as the argument instead of a list of strings?

**Comment by shaobo-he** [comment]
The reason I asked this question is we can, though not ideal, disable checking on certain functions via regex negative look ahead

**Comment by keram88** [comment]
This actually might be very useful for e.g. matching mangled functions.

**Comment by michael-emmi** [comment]
+1 for regex.

You might also (a) consider using regex disjunction instead of a list — whatever is more convenient — and (b) consider whether matching happens at the assembly level — i.e. with "flat" and potentially mangled names — or the source or IR level — i.e. with potentially structured names like "MyModule::myFunction".

**Comment by keram88** [comment]
I think I like leaving it as a list of space separated list to remain consistent with the `--entry-points` flag and allow it to be a list of regex patters. A potential concern is that `$` and `.` are valid characters in identifiers, e.g., used by Kotlin and Rust respectively.

I will have to think more about matching on unmangled names since languages have different mangling schemes (Rust doesn't quite demangle with `c++filt` for example.)

**Review by zvonimir — APPROVED** [review]
Looks good to me.

**Comment by keram88** [comment]
I implemented specifying the functions to check using regular expressions. I made it so that the entire function name must be matched in order to avoid surprises should someone what just one function. However, I'm not sure this is necessarily the best way to do it.

**Review by zvonimir — APPROVED** [review]
Looks good to me.

**Comment by shaobo-he** [comment]
LGTM.

**Review by shaobo-he — APPROVED** [review]

**Pull request merged**
