### PR TITLE
Fix unsound region splitting.

### LINKED ISSUE #258: Unsound region assignment with nested structs
Given the following code, Smack somehow assigns distinct regions to the memory accesses of functions `f` and `g` even though they ought to alias due to identical call-site arguments `&t.z`; both assertions ought to hold, but the first fails given given Smack’s region assignment.
````
#include <smack.h>

struct S {
  int w;
};

struct T {
  int x;
  struct S y;
  struct S z;
};

void f(struct S *state)
{
  state->w = 0;
}

void g(struct S *state)
{
  state->w = 1;
}

int main(void) {
  struct T t;

  f(&t.y);
  f(&t.z);
  g(&t.z);
  	
  assert(t.y.w == 0);
  // ALSO: assert(t.z.w == 1);

  return 0;
}
````

### PR DESCRIPTION
**Pull request by michael-emmi**
* when some equivalent DSA nodes have distinct collapsed status
* fixes #258

### CODE REVIEW

**Comment by michael-emmi** [comment]
Can we merge this?

**Comment by zvonimir** [comment]
@shaobo-he : please run this on SVCOMP as soon as you can. I am a bit worried that this might (significantly) influence the scalability of SMACK, and so it would be good to double-check that.

**Comment by shaobo-he** [comment]
@zvonimir Ok. I will run it right now.

**Comment by michael-emmi** [comment]
Great point; completely forgot to add regressions; added now; will merge after CI success.

**Pull request merged**
