### PR TITLE
Updated Z3 URL. Fixed Boogie installation. Made installation resumable.

### PR DESCRIPTION
**Pull request by cogumbreiro**
SMACK+Vagrant was not working; host used is Ubuntu 15.04.

### CODE REVIEW

**Comment by zvonimir** [comment]
Hi Tiago,
First of all, thanks for your interest in SMACK and for your help!
First of all, I would like to point out that we've been trying to follow this branching model for SMACK:
http://nvie.com/posts/a-successful-git-branching-model/
That means that we never commit straight into master branch, or create pull requests from master branch. We use the develop branch for that. So please initiate this pull request for the develop branch first. Thanks!

**Comment by pierreganty** [comment]
@zvonimir you might want to know that github is supporting a particular feature
which points to contributing guidelines (that you put in file named `CONTRIBUTING.md`) 
at the time of submitting of contribution.
More [here](https://github.com/blog/1184-contributing-guidelines).

**Comment by cogumbreiro** [comment]
@pierreganty @zvonimir 

Including these guidelines would be very helpful as it would've prevented me from working on the wrong branch.

**Comment by zvonimir** [comment]
@pierreganty, excellent suggestion. I just did this and pushed. Hopefully this will prevent at least some confusion in the future. We'll keep expanding our guidelines as we see fit. Thanks guys!

**Pull request closed without merging**
